version: '3.8'

services:
  db:
    container_name: xparking_db
    image: postgres
    restart: always
    ports:
      - "2010:5432"  # Corrected spacing
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data_xparking:/var/lib/postgresql/data

volumes:
  db_data_xparking:
